version: "3.3"
services:

  job_joc_master:
    build: job_joc_master
    container_name: job_joc_master
    links:
      - database:mariadb
      - cluster_agent1
      - cluster_agent2
      - cluster_agent3
    volumes:
      - $PWD/datastore:/opt/jobscheduler/data/scheduler/config/live
    ports:
      - "4446:4446"
      - "40444:40444"
    environment:
      DB_SERVER_PORT: 3306
      DB_SERVER_HOST: mariadb
      DB_SERVER_USER: jobscheduler
      DB_SERVER_PASSWORD: jobscheduler
      DB_SERVER_DATABASE: jobscheduler

  database:
    image: mariadb:latest
    container_name: database
    environment:
      MYSQL_USER: jobscheduler
      MYSQL_USER: jobscheduler
      MYSQL_PASSWORD: jobscheduler
      MYSQL_ROOT_PASSWORD: scheduler
      MYSQL_DATABASE: jobscheduler

  cluster_agent1:
    build: cluster_agent
    container_name: cluster_agent1

  cluster_agent2:
    build: cluster_agent
    container_name: cluster_agent2

  cluster_agent3:
    build: cluster_agent
    container_name: cluster_agent3

